caches:
  - name: bazel
    cache_key:
      - gazelle-py-bazel-v2
      - agent: pipeline
      - agent: os
      - agent: arch
      - env: USE_BAZEL_VERSION
      - agent: step
        fallback_limit: true
      - env: BUILDKITE_COMMIT
    target_paths:
      - /tmp/gazelle-py-ci/repository
      - /tmp/gazelle-py-ci/disk
