agents:
  queue: oss

steps:
  - label: "bazel 9.0.0 test (linux-x86_64)"
    key: bazel-test-9-0-0
    command: "bash .buildkite/bazel.sh test"
    env:
      USE_BAZEL_VERSION: "9.0.0"
    timeout_in_minutes: 60
    cache:
      name: gazelle-py-bazel-tests-9-0-0
      size: 40g
      paths: ["/tmp/gazelle-py-ci"]
    artifact_paths: "bazel-testlogs/**/test.log;bazel-testlogs/**/test.xml"

  - label: "bazel 8.6.0 test (linux-x86_64)"
    key: bazel-test-8-6-0
    command: "bash .buildkite/bazel.sh test"
    env:
      USE_BAZEL_VERSION: "8.6.0"
    timeout_in_minutes: 60
    cache:
      name: gazelle-py-bazel-tests-8-6-0
      size: 40g
      paths: ["/tmp/gazelle-py-ci"]
    artifact_paths: "bazel-testlogs/**/test.log;bazel-testlogs/**/test.xml"

  - label: "examples / bazel 9.0.0"
    key: examples-9-0-0
    command: "bash .buildkite/bazel.sh examples"
    env:
      USE_BAZEL_VERSION: "9.0.0"
    timeout_in_minutes: 60
    cache:
      name: gazelle-py-bazel-examples-9-0-0
      size: 40g
      paths: ["/tmp/gazelle-py-ci"]
    artifact_paths: "examples/*/bazel-testlogs/**/test.log;examples/*/bazel-testlogs/**/test.xml"

  - label: "examples / bazel 8.6.0"
    key: examples-8-6-0
    command: "bash .buildkite/bazel.sh examples"
    env:
      USE_BAZEL_VERSION: "8.6.0"
    timeout_in_minutes: 60
    cache:
      name: gazelle-py-bazel-examples-8-6-0
      size: 40g
      paths: ["/tmp/gazelle-py-ci"]
    artifact_paths: "examples/*/bazel-testlogs/**/test.log;examples/*/bazel-testlogs/**/test.xml"

  - label: "Verify commit hooks"
    key: verify-hooks
    if: build.pull_request.id != null
    command: "bash .buildkite/verify-hooks.sh"
    timeout_in_minutes: 10
